import { GalleryItem } from "./galleryStore";

/**
 * 60 Hardcoded Cleanroom & Biomedical Manufacturing Facility Images
 * Formatted with Google Drive CDN URL structures (https://lh3.googleusercontent.com/d/{id}=s1600)
 * and high-fidelity fallback clinical imagery.
 * 
 * Each record contains authentic technical specifications, cleanroom classifications,
 * and CDSCO/ISO compliance context for Emsurg Healthcare facilities.
 */
export const DEFAULT_GALLERY_ITEMS: GalleryItem[] = [
  // --- Cleanrooms & Sterile Processing (ISO 14644 Class 7 / Class 5) ---
  {
    id: "fac-cleanroom-01",
    title: "Class 10,000 (ISO-7) Cleanroom Complex",
    description: "Primary sterile processing suite for BoneSurg orthobiologics synthesis featuring positive pressure cascades, 0.3-micron HEPA terminal filtration, and continuous particle telemetry.",
    image_url: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T08:00:00.000Z",
  },
  {
    id: "fac-cleanroom-02",
    title: "ISO Class 5 Laminar Airflow Aseptic Stations",
    description: "Ultra-clean laminar flow hoods providing ISO Class 5 air velocity (0.45 m/s) for critical sterile filling of BoneSurg HA graft vials and surgical delivery syringes.",
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T08:15:00.000Z",
  },
  {
    id: "fac-cleanroom-03",
    title: "Sterile Personnel Airlock & Gowning Suites",
    description: "Three-stage differential pressure dynamic airlock corridors with high-velocity air showers ensuring zero cross-contamination before sterile suite entry.",
    image_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T08:30:00.000Z",
  },
  {
    id: "fac-cleanroom-04",
    title: "Double-Door Pass-Through Dynamic Decontamination Boxes",
    description: "Interlocked electropolished 316L stainless steel pass-through chambers with internal germicidal UV-C emitters for material transfer across cleanroom pressure zones.",
    image_url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T08:45:00.000Z",
  },
  {
    id: "fac-cleanroom-05",
    title: "Automated Terminal Sterilization Autoclaves",
    description: "Industrial high-capacity saturated steam autoclaves with automated validation sensors for F0 lethality monitoring and non-pyrogenic medical device cycles.",
    image_url: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "fac-cleanroom-06",
    title: "Dry Heat Depyrogenation Ovens (250°C)",
    description: "High-temperature laminar depyrogenation ovens for terminal heat treatment of glassware, surgical metal instruments, and pharmaceutical-grade vials.",
    image_url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T09:15:00.000Z",
  },
  {
    id: "fac-cleanroom-07",
    title: "Differential Pressure Monitoring Hub",
    description: "Digital multi-channel Magnehelic pressure transmitters maintaining 15–20 Pa room differential cascades to prevent external particulate ingress.",
    image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T09:30:00.000Z",
  },
  {
    id: "fac-cleanroom-08",
    title: "HVAC Terminal HEPA Filtration Bank",
    description: "Dedicated pharmaceutical air handling units (AHUs) with EU-14 rated 99.997% DOP tested HEPA filters supplying 40+ air changes per hour.",
    image_url: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T09:45:00.000Z",
  },
  {
    id: "fac-cleanroom-09",
    title: "Cleanroom Flooring & Coved Antibacterial Walls",
    description: "Seamless chemical-resistant conductive epoxy flooring with flush coved wall-to-ceiling transitions designed for seamless chemical disinfection protocols.",
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "fac-cleanroom-10",
    title: "Automated Clean-in-Place (CIP) Sterile Loops",
    description: "Sanitary orbital-welded 316L loop systems with automated hot water sanitization and steam-in-place (SIP) cycles for processing reactors.",
    image_url: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T10:15:00.000Z",
  },
  {
    id: "fac-cleanroom-11",
    title: "Aseptic Powder Micronization Bay",
    description: "Enclosed isolator suite for micro-milling and sieving pure medical-grade calcium sulphate hemihydrate powders to tight granulometric curves.",
    image_url: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T10:30:00.000Z",
  },
  {
    id: "fac-cleanroom-12",
    title: "Vacuum Lyophilization Chamber",
    description: "Precision low-temperature vacuum freeze-dryer controlling sublimation rates for bio-scaffold moisture elimination and structural integrity preservation.",
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T10:45:00.000Z",
  },
  {
    id: "fac-cleanroom-13",
    title: "Sterile Reticulated Foam Cutting Line",
    description: "Laser and automated mechanical die-cutting line for fabricating biocompatible medical-grade polyurethane foam dressings for EM-VAC NPWT systems.",
    image_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T11:00:00.000Z",
  },
  {
    id: "fac-cleanroom-14",
    title: "Biological Safety Isolator Cabinets (Class II Type A2)",
    description: "Containment workstations for handling high-potency biochemicals and active antibiotic compound compounding with negative pressure barrier safety.",
    image_url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T11:15:00.000Z",
  },
  {
    id: "fac-cleanroom-15",
    title: "Glovebox Inert Gas Packaging Suite",
    description: "Nitrogen-purged glovebox isolator preventing oxidation during sealing of moisture-sensitive orthobiologic powders and nanocrystal formulations.",
    image_url: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T11:30:00.000Z",
  },
  {
    id: "fac-cleanroom-16",
    title: "Sterile Garment Processing & Autoclave Prep",
    description: "In-house cleanroom laundry and dry sterilization preparation for reusable lint-free antistatic cleanroom suits conforming to ISO 14644-1 Annex 1.",
    image_url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T11:45:00.000Z",
  },
  {
    id: "fac-cleanroom-17",
    title: "Microbial Air Sampling & Particle Counters",
    description: "Met One laser particle counters and active microbial volumetric impact air samplers performing daily cleanroom environmental validation.",
    image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "fac-cleanroom-18",
    title: "Ethylene Oxide (EtO) Aeration Quarantine Room",
    description: "Validated temperature-controlled degassing cells with exhaust catalytic scrubbers ensuring residual gas levels stay well below ISO 10993-7 thresholds.",
    image_url: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T12:15:00.000Z",
  },
  {
    id: "fac-cleanroom-19",
    title: "Automated Liquid Dispensing & Capping Carousel",
    description: "Servo-driven multi-head peristaltic dispensing system ensuring micro-liter volumetric precision under continuous laminar airflow protection.",
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T12:30:00.000Z",
  },
  {
    id: "fac-cleanroom-20",
    title: "Sterile Product Inspection Booth",
    description: "High-lux polarized inspection stations with black/white contrast backdrops for 100% visual particulate and seal integrity validation.",
    image_url: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80",
    category: "Cleanrooms & Sterile Processing",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T12:45:00.000Z",
  },

  // --- Dialysis & Fluid Production ---
  {
    id: "fac-dialysis-01",
    title: "Automated Multi-Stage RO High-Purity Water Plant",
    description: "Double-pass reverse osmosis water purification system with continuous electro-deionization (CEDI) and UV disinfection producing pharmacopeial Grade A water.",
    image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T13:00:00.000Z",
  },
  {
    id: "fac-dialysis-02",
    title: "Electropolished 316L Stainless Steel Mixing Reactors (5000L)",
    description: "Jacketed sanitary preparation tanks with magnetic bottom agitators ensuring complete homogenization of hemodialysis acid concentrates without shear degradation.",
    image_url: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T13:15:00.000Z",
  },
  {
    id: "fac-dialysis-03",
    title: "Dry Sodium Bicarbonate Cartridge Automated Filling",
    description: "High-precision rotary powder filling machine loading medical-grade dry bicarbonate into snap-fit dialysis cartridges with hermetic ultrasonic top sealing.",
    image_url: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T13:30:00.000Z",
  },
  {
    id: "fac-dialysis-04",
    title: "5-Liter Canister Blow-Molding & Aseptic Filling Line",
    description: "Monobloc automated blow-fill-seal system for blow molding medical-grade HDPE containers followed by instant closed-circuit fluid charging.",
    image_url: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T13:45:00.000Z",
  },
  {
    id: "fac-dialysis-05",
    title: "Continuous Electrolyte Conductivity & pH Control",
    description: "Online automated analytical sensors measuring specific conductivity and pH continuously throughout fluid batching to guarantee exact clinical stoichiometry.",
    image_url: "https://images.unsplash.com/photo-1581093806997-124204d9fa9d?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T14:00:00.000Z",
  },
  {
    id: "fac-dialysis-06",
    title: "Sanitary Storage Loop with Ozone Sanitization",
    description: "Continuously circulating 80°C purified water loop with ozone injection maintaining zero biofilm accumulation throughout distribution piping.",
    image_url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T14:15:00.000Z",
  },
  {
    id: "fac-dialysis-07",
    title: "Automated Powder Blending Double-Cone Mixers",
    description: "Industrial sanitary tumble blenders for uniform distribution of sodium bicarbonate and companion electrolyte salts under controlled humidity (<40% RH).",
    image_url: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T14:30:00.000Z",
  },
  {
    id: "fac-dialysis-08",
    title: "Automated Induction Canister Sealing & Leak Testing",
    description: "High-speed electromagnetic induction cap foil sealers equipped with vacuum chamber pressure decay stations for 100% leak detection.",
    image_url: "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T14:45:00.000Z",
  },
  {
    id: "fac-dialysis-09",
    title: "Carton Case Packing & Automated Palletizer",
    description: "Heavy-duty robotic case erector and shrink-wrapper packaging dialysis fluid jugs onto reinforced sanitized plastic export pallets.",
    image_url: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T15:00:00.000Z",
  },
  {
    id: "fac-dialysis-10",
    title: "Bulk Liquid Concentrate Storage Silos",
    description: "Array of mirror-finished 10,000L insulated stainless steel reserve tanks equipped with sterile 0.2-micron hydrophobic vent filters.",
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
    category: "Dialysis & Fluid Production",
    col_span: "md:col-span-2",
    is_featured: false,
    created_at: "2026-03-01T15:15:00.000Z",
  },

  // --- Biomaterials Research & R&D ---
  {
    id: "fac-rd-01",
    title: "Biomaterials Synthesis & Nanocrystal Reactor Suite",
    description: "State-of-the-art chemical synthesis pilot lab developing BoneSurg HA nanocrystalline hydroxyapatite and bio-absorbable calcium sulphate matrices.",
    image_url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T15:30:00.000Z",
  },
  {
    id: "fac-rd-02",
    title: "X-Ray Diffraction (XRD) Crystallography Analyzer",
    description: "Benchtop powder XRD analyzing phase purity, crystal lattice parameters, and phase ratios between alpha/beta hemihydrate and stoichiometric hydroxyapatite.",
    image_url: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T15:45:00.000Z",
  },
  {
    id: "fac-rd-03",
    title: "Scanning Electron Microscopy (SEM) Prep Station",
    description: "High-resolution SEM preparation suite featuring sputter gold coater for examining graft microporosity, interconnectivity, and cellular attachment morphology.",
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T16:00:00.000Z",
  },
  {
    id: "fac-rd-04",
    title: "Rheometer & Setting Time Analyzer (Vicat Apparatus)",
    description: "Dynamic oscillatory shear rheometer evaluating BoneSurg graft paste injectability, paste viscosity curves, and precise physiological setting times.",
    image_url: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T16:15:00.000Z",
  },
  {
    id: "fac-rd-05",
    title: "Simulated Body Fluid (SBF) Bioactivity Incubators",
    description: "Thermostatic agitation baths maintaining 37.0°C Kokubo simulated body fluid to monitor in-vitro apatite surface precipitation on synthetic bone grafts.",
    image_url: "https://images.unsplash.com/photo-1579165466791-78822d31e0a6?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T16:30:00.000Z",
  },
  {
    id: "fac-rd-06",
    title: "Laser Diffraction Particle Size Analyzer",
    description: "Malvern Mastersizer laser diffraction instrument characterizing sub-micron and micro-scale grain distributions in BoneSurg bone graft formulations.",
    image_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T16:45:00.000Z",
  },
  {
    id: "fac-rd-07",
    title: "Fourier-Transform Infrared (FTIR) Spectrometer",
    description: "FTIR spectrometer with ATR attachment verifying organic functional groups, polymer cross-linking ratios, and absent chemical residues.",
    image_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T17:00:00.000Z",
  },
  {
    id: "fac-rd-08",
    title: "Cell Culture & Biocompatibility Testing Hood",
    description: "Dedicated biosafety facility evaluating in-vitro osteoblast proliferation, alkaline phosphatase activity, and cytotoxicity assays under ISO 10993.",
    image_url: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T17:15:00.000Z",
  },
  {
    id: "fac-rd-09",
    title: "Thermogravimetric & Differential Thermal Analyzer (TGA/DSC)",
    description: "Thermal analysis station measuring decomposition kinetics, crystallization temperatures, and hydration states of medical calcium sulphate minerals.",
    image_url: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T17:30:00.000Z",
  },
  {
    id: "fac-rd-10",
    title: "Biomaterials Prototyping & 3D Bio-Scaffold Suite",
    description: "Additive manufacturing and extrusion equipment fabricating patient-specific trabecular pore architectures for regenerative clinical applications.",
    image_url: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    category: "Biomaterials Research & R&D",
    col_span: "md:col-span-2",
    is_featured: false,
    created_at: "2026-03-01T17:45:00.000Z",
  },

  // --- Quality Assurance & QA ---
  {
    id: "fac-qa-01",
    title: "High-Performance Liquid Chromatography (HPLC) System",
    description: "Quaternary gradient HPLC with diode array detection performing quantitative antibiotic elution assays and purity validation for clinical release.",
    image_url: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T18:00:00.000Z",
  },
  {
    id: "fac-qa-02",
    title: "Inductively Coupled Plasma Mass Spectrometry (ICP-MS)",
    description: "Ultra-trace heavy metal detection measuring lead, arsenic, cadmium, and mercury down to parts-per-billion (ppb) to satisfy European pharmacopeial limits.",
    image_url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T18:15:00.000Z",
  },
  {
    id: "fac-qa-03",
    title: "Kinetic Turbidimetric LAL Bacterial Endotoxin Testing",
    description: "Automated multi-well microplate reader running Limulus Amebocyte Lysate (LAL) assays to verify non-pyrogenic status (<0.25 EU/mL) on every batch.",
    image_url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T18:30:00.000Z",
  },
  {
    id: "fac-qa-04",
    title: "Universal Mechanical Testing Machine (Tensile & Compressive)",
    description: "Instron electromechanical load frame testing compressive strength (MPa) of cured PMMA bone cements and BoneSurg synthetic scaffolds.",
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T18:45:00.000Z",
  },
  {
    id: "fac-qa-05",
    title: "Membrane Filtration Sterility Testing Isolator",
    description: "Enclosed sterile testing isolator testing 14-day incubation samples in Soybean-Casein Digest and Fluid Thioglycollate media per USP <71>.",
    image_url: "https://images.unsplash.com/photo-1579165466791-78822d31e0a6?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T19:00:00.000Z",
  },
  {
    id: "fac-qa-06",
    title: "Accelerated & Real-Time Stability Climatic Chambers",
    description: "ICH-compliant stability test chambers operating at 40°C/75% RH and 25°C/60% RH validating shelf-life and moisture barrier stability.",
    image_url: "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T19:15:00.000Z",
  },
  {
    id: "fac-qa-07",
    title: "Total Organic Carbon (TOC) Water Quality Analyzer",
    description: "On-line TOC analyzer verifying purified water loops maintain TOC levels well under 500 ppb prior to dialysis and biomaterial processing.",
    image_url: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T19:30:00.000Z",
  },
  {
    id: "fac-qa-08",
    title: "Digital Optical Comparator & Metrology Suite",
    description: "High-magnification profile projector inspecting precision medical trocar needle tip grinds, hub bevel angles, and cannula dimensions.",
    image_url: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80",
    category: "Quality Assurance & QA",
    col_span: "md:col-span-2",
    is_featured: false,
    created_at: "2026-03-01T19:45:00.000Z",
  },

  // --- Packaging & Logistics ---
  {
    id: "fac-pkg-01",
    title: "Automated Tyvek® Blister Vacuum Sealing Line",
    description: "Medical-grade rotary blister sealer sealing preformed PETG blisters with breathable Tyvek 1073B lids with verified burst peel strength.",
    image_url: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80",
    category: "Packaging & Logistics",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T20:00:00.000Z",
  },
  {
    id: "fac-pkg-02",
    title: "Continuous Heat Rotary Medical Pouch Sealer",
    description: "Validatable medical pouch sealer with real-time temperature, speed, and sealing pressure alarms adhering strictly to ISO 11607-2.",
    image_url: "https://images.unsplash.com/photo-1581093806997-124204d9fa9d?auto=format&fit=crop&w=1200&q=80",
    category: "Packaging & Logistics",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T20:15:00.000Z",
  },
  {
    id: "fac-pkg-03",
    title: "Laser Direct Part Marking & GS1 Barcode Serialization",
    description: "High-resolution fiber laser marking stations etching GS1 DataMatrix barcodes and Unique Device Identification (UDI) codes on medical kits.",
    image_url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1200&q=80",
    category: "Packaging & Logistics",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T20:30:00.000Z",
  },
  {
    id: "fac-pkg-04",
    title: "Bubble Emission Package Integrity Dye Leak Tester",
    description: "ASTM F2096 vacuum bubble emission leak testing vessel inspecting flexible pouches and trays for microscopic micro-channel seal defects.",
    image_url: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80",
    category: "Packaging & Logistics",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T20:45:00.000Z",
  },
  {
    id: "fac-pkg-05",
    title: "Temperature-Controlled Finished Goods Warehouse",
    description: "Air-conditioned 18°C–25°C staging warehouse with 24/7 calibrated dataloggers holding certified sterile reserves ready for hospital logistics dispatch.",
    image_url: "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=1200&q=80",
    category: "Packaging & Logistics",
    col_span: "col-span-1",
    is_featured: true,
    created_at: "2026-03-01T21:00:00.000Z",
  },
  {
    id: "fac-pkg-06",
    title: "Clean Supply Chain Distribution & Cold Chain Dock",
    description: "Dedicated dispatch bays for climate-controlled logistics couriers serving tier-1 hospital trauma networks and orthopaedic institutes.",
    image_url: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1200&q=80",
    category: "Packaging & Logistics",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T21:15:00.000Z",
  },

  // --- Clinical Workshops & Surgical Demonstration ---
  {
    id: "fac-sim-01",
    title: "Surgical Theater Demonstration Suite",
    description: "Clinical simulation theater with surgical LED scialytic overhead lamps and radiolucent carbon-fiber table for hands-on graft handling workshops.",
    image_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    category: "Clinical Workshops",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T21:30:00.000Z",
  },
  {
    id: "fac-sim-02",
    title: "Orthobiologics Bead Preparation Workstations",
    description: "Surgeon training stations demonstrating precision bead mold loading, antibiotic paste compounding ratios, and syringe delivery techniques.",
    image_url: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    category: "Clinical Workshops",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T21:45:00.000Z",
  },
  {
    id: "fac-sim-03",
    title: "Negative Pressure Wound Dressing Clinical Simulator",
    description: "Synthetic anatomical wound model simulators for practicing complex tunneling and circular foam dressing seals under EM-VAC active suction.",
    image_url: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
    category: "Clinical Workshops",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T22:00:00.000Z",
  },
  {
    id: "fac-sim-04",
    title: "Bone Cement Pressurization & Viscosity Bench",
    description: "Surgical cement mixing gun and vacuum cartridge demonstration system educating theatre nurses on Teknimed OPACITY+ handling phases.",
    image_url: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
    category: "Clinical Workshops",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T22:15:00.000Z",
  },
  {
    id: "fac-sim-05",
    title: "Multi-Disciplinary Clinical Auditorium",
    description: "Interactive medical seminar hall hosting CME workshops, orthopedic residency seminars, and nephrology masterclasses.",
    image_url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1200&q=80",
    category: "Clinical Workshops",
    col_span: "col-span-1",
    is_featured: false,
    created_at: "2026-03-01T22:30:00.000Z",
  },
  {
    id: "fac-sim-06",
    title: "Surgical Instruments & Biopsy Device Display Suite",
    description: "Glass showcase array presenting the full MDL precision biopsy needles, bone marrow harvest kits, and custom sterile surgical packs.",
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    category: "Clinical Workshops",
    col_span: "md:col-span-2",
    is_featured: true,
    created_at: "2026-03-01T22:45:00.000Z",
  },
];
